#
# Copyright (c) 2020, Elikya Corporation.
#

#English file
sales=Ventes
new_sale=Nouvelle vente
sale=Vente
products=Produits
product=Produit
help=Aide
about=A Propos
name=Nom
description=Description
save=Sauver
categories=Cat\u00e9gories
category=Cat\u00e9gorie
table_prompt=Aucune donn\u00e9e trouv\u00e9e
stock=Stock
quantities=Quantit\u00e9s
deletion=Suppression
deletion_question=Etes-vous s\u00fbr de vouloir supprimer la selection courante?
yes=Oui
providers=Fournisseurs
provider=Fournisseur
unit_price=P.U.
maximum_quantity=Qt\u00e9. Max.
minimum_quantity=Qt\u00e9. Min.
stock_quantity=Qt\u00e9. Stock
date=Date
time=Heure
new_product=Nouveau Produit
search=Chercher ...
options=Options
general=G\u00e9n\u00e9ral
phone=N\u02da de T\u00e9l\u00e9phone
phone_number_pattern=(+Pays) Num\u00e9ro
language=Langue
my_rhoe=Mon Rhoe
enterprise=Entreprise
slogan=Slogan
my_enterprise=Mon Entreprise
password=Mot de passe
group_by=Grouper par
more=Plus
address=Adresse
address_pattern=N\u02da, Rue, Ville, Pays
email=Email
edit=Modifier
copy=Copier
delete=Supprimer
select=S\u00e9lectionner
from=Du
to=Au
price=Prix
price_tax=Prix T.
enterprise_name=Nom de l'entreprise
phone_number=T\u00e9l\u00e9phone
file_explorer=Explorateur de Fichiers
quantity=Quantit\u00e9
product_moves=R\u00e9sum\u00e9 Produit
resume=R\u00e9sum\u00e9
undo=Pr\u00e9c\u00e9dent
redo=Suivant
required_field_empty=Champ(s) obligatore(s) vide(s)
no=Non
invalid_email=Adresse Mail incorrecte
invalid_phone=Num\u00e9ro de t\u00e9l\u00e9phone incorrect
invalid_address=Adresse Physique incorrecte
export=Exporter
data_exported=Donn\u00e9es export\u00e9es avec succ\u00e8s
serial_number=N\u00b0 S\u00e9rie
decimals=D\u00e9cimales
decimals_number=Nombre de d\u00e9cimales
product_number=N\u00b0 Produit
invalid_quantities=Diff\u00e9rence des quantit\u00e9s invalide
month=Mois
year=Ann\u00e9e
invalid_period=P\u00e9riode Invalide
none=Aucun
empty_fields=Interrompre
find_all=Tout Afficher
products_number=Nombre de Produits
products_quantity=Qt\u00e9. de Produits
taxes=Taxes
total_price=Prix Tot.
percent=Pourcentage
cost=Co\u00fbt
next=Suivant
sale_number=N\u00b0 Vente
previous=Pr\u00e9cedent
total_price_tax=Prix Tot. T.
sale_added=Vente enr\u00e9gistr\u00e9e avec succ\u00e8s
edit_product=Modifier Produit
day_month=Jour (Mois)
day_week=Jour (Semaine)
default_currency=Monnaie par Defaut
currency=Unit\u00e9 Monn\u00e9taire
reports=R\u00e9cap
authentication=Authentification
log_in=Log In
about_text=Elikya Rhoe est un logiciel de gestion de magasin développé par Elikya, dans le but de vous aider à mieux gérer votre entreprise au quotidien. Il traite et présente vos données commerciales avec une grande simplicité, afin de vous aider à prendre de bonnes décisions pour l'avenir de votre magasin. Même sans expérience en comptabilité ou en gestion, vous pouvez toujours diriger votre entreprise comme un grand gestionnaire.
monday=Lundi
tuesday=Mardi
wednesday=Mercredi
thursday=Jeudi
friday=Vendredi
saturday=Samedi
sunday=Dimanche
january=Janvier
february=F\u00e9vrier
march=Mars
april=Avril
may=Mai
june=Juin
july=Juillet
august=Ao\u00fbt
september=Septembre
october=Octobre
november=Novembre
december=D\u00e9cembre
category_number=N\u00b0 Cat\u00e9gorie
others=Autres
password_forgotten=Mot de Passe oubli\u00e9
subscriber=Compte
username=Username
verify=V\u00e9rifier
new_password=Nouveau Mot de Passe
your_business=Votre business
business_few_words=Un court texte sur votre entreprise
deadline=Ech\u00e9ance
action_on_save=Actions Sur Sauvegarde
close_new_sale=Fermer Nouvelle Vente
close_new_product=Fermer Nouveau Produit
remove=R\u00e9tirer
products_limit_qty=Qt\u00e9. Limite des Produits  \u00e0 la Vente
limit=Limite
category_name_taken=Nom de la Cat\u00e9gorie d\u00e9j\u00e0 pris
provider_name_taken=Nom du Fournisseur d\u00e9j\u00e0 pris
tax_name_taken=Nom de la Taxe d\u00e0j\u00e0 prise
category_saved=Category ajout\u00e9e avec succ\u00e8s
category_updated=Category modifi\u00e9e avec succ\u00e8s
min_qty_alert=Qt\u00e9. Min. d\u00e9pass\u00e9
max_qty_alert=Qt\u00e9. Max. surpass\u00e9
unit_price_tax=P.U. T.
product_added=Produit ajout\u00e9 avec succ\u00e8s
product_edited=Produit modifi\u00e9 avec avec succ\u00e8s
find_by_period=Afficher par p\u00e9riode
category_deleted=Categorie supprim\u00e9e avec avec succ\u00e8s
provider_deleted=Fournisseur supprim\u00e9 avec avec succ\u00e8s
provider_updated=Fournisseur modifi\u00e9 avec avec succ\u00e8s
compute_by=Calculer Par
no_update=Rien \u00e0 Modifier
sale_created=Vendu
sale_deletion=V. Supprim\u00e9e
# suppress inspection "UnusedProperty"
prod_created=Cr\u00e9\u00e9
# suppress inspection "UnusedProperty"
prod_increased=Approvisionn\u00e9
# suppress inspection "UnusedProperty"
prod_decreased=Retir\u00e9
action=Action
periods=P\u00e9riodes
sale_details=R\u00e9sum\u00e9 Vente
no_product=Produit non pr\u00e9sent
barcode=Code-Barres
total_prods_number=Nombre Tot. Produits
total_prods_qty=Qt\u00e9. Tot. Produits
sales_number=Nombre des Ventes
export_all=Exporter Tout
code_validation=Validation Code
enter_code=Saisissez le Code
submit=Soumettre
invalid_code=Code Invalide
no_export_folder=Dossier d'exportation non cre\u00e9
qty=Qt\u00e9.
thank_you=Merci!!!
sale_deleted=Vente supprim\u00e9e avec succ\u00e8s
settings_saved=Param\u00e8 enregistr\u00e9s avec succ\u00e8s
advanced_currency=Options Avanc\u00e9es
default_currency_unit=Unit\u00e9
second_currency=Seconde D\u00e9vise
conversion_value=Rate
invalid_converted_value=Valeur Convertie Invalide
from_client=Argent du Client
money_received=Re\u00e7u
rest=A Remettre
insufficient_amount=Montant Insuffinsant
invalid_numeric_values=Valeurs Numériques Invalides
invalid_tax_value=Valuer de la Taxe invalide
delete_products_first=Veuillez d'abord supprimer les Produits de la selection courante
delete_sales_first=Veuillez d'abord supprimer les Ventes de la selection courante
delete_sale=Supprimer Vente
sale_not_added=Vente non ajout\u00e9e
provider_saved=Fournisseur ajout\u00e9 avec succ\u00e8s
exit_question=Voulez-vous vraiment quitter Elikya Rhoe
exit_title=Confirmation Sortie
do_not_ask_again=Ne plus me demander
invalid_min_qty=Qt\u00e9. Min. Invalide
no_tax_value=Aucune valeur num\u00e9rique
stock_up=Approvisionner
withdraw=Retirer
cancel=Annuler
reason=Raison
move_currency=D\u00e9vise Action
move_rate=Taux Action
folder_error=Impossible d'ouvir l'Explorateur des Fichiers
synchronize=Synchronizer
license=Your License
optional=Optionnel
your_account=Votre Compte
server_error=Impossible de se connecter au serveur
mail_address=Adresse Mail
check_email=Veuillez consulter votre compte mail pour avoir le code
mail_taken=Adresse Mail d\u00e9j\u00e8 prise
phone_taken=Num\u00e9ro de T\u00e9 d\u00e9j\u00e8 pris
email_problem=Nous avons rencontr\u00e9 un probl\u00e8me en vous envoyant le Code
products_resume=R\u00e0sum\u00e9 Produits
provide_second_currency=Veuillez entrer la seconde d\u00e9vise
password_prompt=Entrez le text ...
how_to=Comment Utiliser
cannot_update=Addresse mail pas modifi\u00e9
no_payment=Pas de nouveau payment
update_license=Veuillez renouveller votre license
restart_app=Veuillez reouvrir Elikya Rhoe afin d'activer votre license
product_duplicate=Nom, N\u00b0 S\u00e9rie ou Code-barres du produit d\u00e9j\u00e0 pris
moves=Mouvements
wrong_password=Mot de passe invalide
scan_barcode=Scannez un code-barres ...
subject=Sujet
content=Contenu
feedback=R\u00e9action
open_licenses=Autres Licences
feedback_submitted=R\u00e0action soumise avec succ\u00e8s