#
# Copyright (c) 2020, Elikya Technology.
#

#English file
sales=Sales
sale=Sale
products=Products
product=Product
help=Help
about=About
name=Name
description=Description
save=Save
categories=Categories
category=Category
table_prompt=No item found
stock=Stock
quantities=Quantities
deletion=Deletion
deletion_question=Are you sure to delete the current selection?
yes=Yes
providers=Providers
provider=Provider
unit_price=U.P.
maximum_quantity=Max. Qty.
minimum_quantity=Min. Qty.
stock_quantity=Stock Qty.
quantity=Quantity
date=Date
new_product=New Product
new_sale=New Sale
search=Search ...
options=Options
general=General
phone=Phone
time=Time
language=Language
my_rhoe=My Rhoe
enterprise=Enterprise
my_enterprise=My Enterprise
password=Password
group_by=Group By
more=More
address=Address
address_pattern=N\u02da, Street, City, Country
email=Email
edit=Edit
copy=Copy
delete=Delete
select=Select
from=From
to=To
price=Price
price_tax=Price T.
enterprise_name=Enterprise Name
phone_number=Phone Number
phone_number_pattern=(+Country) Number
file_explorer=File Explorer
product_moves=Product Resume
resume=Resume
undo=Undo
redo=Redo
required_field_empty=Required field(s) empty
no=No
invalid_email=Invalid Mail Address
invalid_phone=Invalid Phone Number
invalid_address=Invalid Physical Address
export=Export
data_exported=Data successfully exported
serial_number=Serial N\u02da
decimals=Decimals
decimals_number=Decimals Number
product_number=Product N\u02da
invalid_quantities=Invalid quantity values
month=Month
year=Year
invalid_period=Invalid Period
none=None
empty_fields=Abort
find_all=Find All
products_number=Products Number
taxes=Taxes
total_price=Tot. Price
percent=Percent
cost=Cost
next=Next
products_quantity=Products Qty.
sale_number=Sale N\u02da
previous=Previous
total_price_tax=Tot. Price T.
sale_added=Sale successfully added
edit_product=Edit Product
day_month=Day of Month
day_week=Day of Week
default_currency=Default Currency
currency=Currency
reports=Balance Sheet
authentication=Authentication
log_in=Log In
about_text=Elikya Rhoe is a store-management software developed by Elikya, with the goal to help you better manage your business on a daily-basis. It processes and presents your business data with a great simplicity in order to help you make good decisions for the future of your store.
monday=Monday
tuesday=Tuesday
wednesday=Wednesday
thursday=Thursday
friday=Friday
saturday=Saturday
sunday=Sunday
january=January
february=February
march=March
april=April
may=May
june=June
july=July
august=August
september=September
october=October
november=November
december=December
scan_barcode=Scan a Barcode
category_number=Category N\u00b0
others=Others
password_forgotten=Password forgotten
username=Username
verify=Verify
your_business=Your Business
business_few_words=A few words about your business
deadline=Deadline
action_on_save=Actions on Save
close_new_sale=Close New Sale
close_new_product=Close New Product
remove=Remove
products_limit_qty=Products' Limit Qty. On Sale
limit=Limit
category_name_taken=Category's name already taken
provider_name_taken=Provider's name already taken
tax_name_taken=Tax name already taken
category_saved=Category successfully saved
category_updated=Category successfully updated
provider_saved=Provider successfully saved
provider_updated=Provider successfully updated
provider_deleted=Provider successfully deleted
category_deleted=Category successfully deleted
min_qty_alert=Min. Qty. subceeded
max_qty_alert=Max. Qty. exceeded
settings_saved=Settings successfully saved
unit_price_tax=U.P. T.
product_added=Product successfully added
product_edited=Product successfully edited
find_by_period=Find by period
compute_by=Compute By
no_update=Nothing to update
sale_created=Sold
sale_deletion=Sale Deleted
# suppress inspection "UnusedProperty"
prod_created=Created
# suppress inspection "UnusedProperty"
prod_increased=Stocked Up
# suppress inspection "UnusedProperty"
prod_decreased=Withdrawn
action=Action
periods=Periods
sale_details=Sale Resume
no_product=Product not present
barcode=Barcode
total_prods_number=Tot. Products Number
total_prods_qty=Tot. Products Qty.
sales_number=Sales Number
export_all=Export All
code_validation=Code Validation
enter_code=Enter the code
submit=Submit
invalid_code=Invalid Code
no_export_folder=Exportation folder not created
qty=Qty.
thank_you=Thank You!!!
sale_deleted=Sale successfully deleted
advanced_currency=Advanced Options
default_currency_unit=Unit
second_currency=Second Currency
conversion_value=Rate
invalid_converted_value=Invalid Converted Value
from_client=Client's Money
money_received=Received
rest=Rest
insufficient_amount=Insufficient Amount
invalid_numeric_values=Invalid Numeric Values
invalid_tax_value=Invalid tax value
delete_products_first=Please, delete the current selection's Products first
delete_sales_first=Please, delete the current selection's Sales first
delete_sale=Delete Sale
sale_not_added=Sale not Added
exit_question=Do you really want to exit Elikya Rhoe?
exit_title=Exit Confirmation
do_not_ask_again=Do not ask me again
invalid_min_qty=Invalid Min. Qty.
no_tax_value=No numeric value
stock_up=Stock Up
withdraw=Withdraw
cancel=Cancel
reason=Reason
move_currency=Action Currency
move_rate=Action Rate
synchronize=Synchronize
license=Your License
optional=Optional
mail_address=Mail Address
server_error=Can not connect to the server
your_account=Your Account
check_email=Please, check your mail inbox to get the code
mail_taken=Mail Address already taken
products_resume=Products Resume
provide_second_currency=Please, enter the second currency
password_prompt=Enter the text ...
no_payment=No new payment
update_license=Please, renew your license
restart_app=Please, restart Elikya Rhoe to fully reactivate your license
product_duplicate=Product's Name, Serial N\u02da, or Barcode already taken
moves=Moves
wrong_password=Invalid password
subject=Subjet
content=Content
feedback=Feedback
feedback_submitted=Feedback successfully sent.
not_printed=Printing Error
db_error=Unknown Datasource