#
# Copyright (c) 2020, Elikya Technology.
#

spring.h2.console.enabled=false
spring.h2.console.settings.web-allow-others=false
spring.h2.console.settings.trace=false

spring.jpa.database=h2
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.H2Dialect

spring.h2.console.path=/none

spring.main.web-application-type=none

management.metrics.export.jmx.enabled=false